import {Table, TableHead, TableBody, TableRow, TableCell, Typography} from "@mui/material";

function Timesheet() {
    return(
        <Table>
            <TableHead>
                <TableRow>
                    <TableCell>
                        <Typography
                            variant="body2"
                            fontWeight="bold"
                        >
                            Date
                        </Typography>
                    </TableCell>
                    <TableCell>
                        <Typography
                            variant="body2"
                            fontWeight="bold"
                        >
                            Clock In
                        </Typography>
                    </TableCell>
                    <TableCell>
                        <Typography
                            variant="body2"
                            fontWeight="bold"
                        >
                            Clock Out
                        </Typography>
                    </TableCell>
                    <TableCell>
                        <Typography
                            variant="body2"
                            fontWeight="bold"
                        >
                            Total Hours
                        </Typography>
                    </TableCell>
                    <TableCell>
                        <Typography
                            variant="body2"
                            fontWeight="bold"
                        >
                            Status
                        </Typography>
                    </TableCell>
                </TableRow>
            </TableHead>
            <TableBody>
                <TableRow>
                    <TableCell>
                        2024/01/01
                    </TableCell>
                    <TableCell>
                        9:00AM
                    </TableCell>
                    <TableCell>
                        5:00PM
                    </TableCell>
                    <TableCell>
                        8
                    </TableCell>
                    <TableCell>
                        Accepted
                    </TableCell>
                </TableRow>
                <TableRow>
                    <TableCell>
                        2024/01/02
                    </TableCell>
                    <TableCell>
                        9:00AM
                    </TableCell>
                    <TableCell>
                        5:00PM
                    </TableCell>
                    <TableCell>
                        8
                    </TableCell>
                    <TableCell>
                        Awaiting
                    </TableCell>
                </TableRow>
                <TableRow>
                    <TableCell>
                        2024/01/03
                    </TableCell>
                    <TableCell>
                        9:00AM
                    </TableCell>
                    <TableCell>
                        5:00PM
                    </TableCell>
                    <TableCell>
                        8
                    </TableCell>
                    <TableCell>
                        Rejected
                    </TableCell>
                </TableRow>
            </TableBody>
        </Table>
    )
}
export default Timesheet